package com.example.mytodolist;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

/**
 * Created by core on 16/12/18.
 */

@Entity(tableName = "todo_table")
public class Todo {

    // autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    private int id;

    @NonNull
    @ColumnInfo(name = "todo")
    private String mTodo;


    public Todo(@NonNull String todo) {
        this.mTodo = todo;
    }

    // Room expects only one constructor by default
    @Ignore
    public Todo(int id, @NonNull String todo) {
        this.id = id;
        this.mTodo = todo;
    }

    public String getTodo(){return this.mTodo;}

    public int getId() { return this.id;};

    public void setId(int id) {
        this.id = id;
    }
}